DROP TABLE IF EXISTS FactMaterialTransfers;
DROP TABLE IF EXISTS FactMaterialOrders;

DROP TABLE IF EXISTS DimJunk;
DROP TABLE IF EXISTS DimDate;
DROP TABLE IF EXISTS DimProject;
DROP TABLE IF EXISTS DimWarehouse;
DROP TABLE IF EXISTS DimSupplier;
DROP TABLE IF EXISTS DimMaterial;